from collections.abc import Awaitable, Callable
from datetime import datetime
from typing import Protocol

from .analyzer import MediaAnalysis
from .captures import CaptureVariant, CapturedSource
from .collections import Collection, CollectionItem
from .models import DownloadJob, DownloadSourceType, RequestContext

ProgressCallback = Callable[[DownloadJob], Awaitable[None]]


class DownloadRepository(Protocol):
    async def add(self, job: DownloadJob) -> None: ...
    async def get(self, job_id: str) -> DownloadJob | None: ...
    async def list(self) -> list[DownloadJob]: ...
    async def update(self, job: DownloadJob) -> None: ...
    async def delete(self, job_id: str) -> None: ...


class Downloader(Protocol):
    async def download(
        self,
        job: DownloadJob,
        *,
        preset: str,
        format_id: str | None,
        concurrent_fragments: int,
        retries: int,
        use_aria2: bool,
        request_context: RequestContext,
        source_type: DownloadSourceType,
        capture_id: str | None,
        audio_url: str | None,
        collection_item_id: str | None,
        on_progress: ProgressCallback,
    ) -> DownloadJob: ...

    async def cancel(self, job_id: str) -> None: ...


class Analyzer(Protocol):
    async def analyze(self, url: str, *, request_context: RequestContext) -> MediaAnalysis: ...


class ToolingService(Protocol):
    async def versions(self) -> dict[str, str | None]: ...
    async def update_yt_dlp(self) -> str | None: ...


class CaptureRepository(Protocol):
    async def add(self, capture: CapturedSource) -> CapturedSource: ...
    async def get(self, capture_id: str) -> CapturedSource | None: ...
    async def list(self, limit: int = 50) -> list[CapturedSource]: ...
    async def find_by_source_key(self, source_key: str) -> CapturedSource | None: ...
    async def update(self, capture: CapturedSource) -> CapturedSource: ...
    async def mark_downloaded(self, capture_id: str) -> CapturedSource | None: ...
    async def delete(self, capture_id: str) -> None: ...
    async def replace_variants(self, capture_id: str, variants: 'list[CaptureVariant]') -> None: ...
    async def list_variants(self, capture_id: str) -> 'list[CaptureVariant]': ...
    async def variants_for(self, capture_ids: 'list[str]') -> 'dict[str, list[CaptureVariant]]': ...
    async def find_by_variant_key(self, variant_key: str) -> CapturedSource | None: ...


class CollectionRepository(Protocol):
    async def add_collection(self, collection: Collection) -> Collection: ...
    async def get_collection(self, collection_id: str) -> Collection | None: ...
    async def list_collections(self) -> list[Collection]: ...
    async def rename_collection(self, collection_id: str, name: str) -> Collection | None: ...
    async def delete_collection(self, collection_id: str) -> None: ...

    async def add_item(self, item: CollectionItem) -> CollectionItem: ...
    async def get_item(self, item_id: str) -> CollectionItem | None: ...
    async def list_items(self, collection_id: str) -> list[CollectionItem]: ...
    async def list_items_page(
        self, collection_id: str, *, state: str = 'all', limit: int = 50, offset: int = 0,
    ) -> list[CollectionItem]: ...
    async def collection_counts(self) -> dict[str, tuple[int, int]]: ...
    async def remove_item(self, collection_id: str, item_id: str) -> None: ...
    async def mark_item_downloaded(self, item_id: str, job_id: str) -> None: ...

    async def update_item_metadata(
        self, item_id: str, *, caption: str | None, posted_at: datetime | None,
    ) -> None: ...
