from collections.abc import Awaitable, Callable
from typing import Protocol

from .analyzer import MediaAnalysis
from .captures import CapturedSource
from .models import DownloadJob, DownloadSourceType, RequestContext

ProgressCallback = Callable[[DownloadJob], Awaitable[None]]


class DownloadRepository(Protocol):
    async def add(self, job: DownloadJob) -> None: ...
    async def get(self, job_id: str) -> DownloadJob | None: ...
    async def list(self) -> list[DownloadJob]: ...
    async def update(self, job: DownloadJob) -> None: ...
    async def delete(self, job_id: str) -> None: ...


class Downloader(Protocol):
    async def download(
        self,
        job: DownloadJob,
        *,
        preset: str,
        format_id: str | None,
        concurrent_fragments: int,
        retries: int,
        use_aria2: bool,
        request_context: RequestContext,
        source_type: DownloadSourceType,
        capture_id: str | None,
        on_progress: ProgressCallback,
    ) -> DownloadJob: ...

    async def cancel(self, job_id: str) -> None: ...


class Analyzer(Protocol):
    async def analyze(self, url: str, *, request_context: RequestContext) -> MediaAnalysis: ...


class ToolingService(Protocol):
    async def versions(self) -> dict[str, str | None]: ...
    async def update_yt_dlp(self) -> str | None: ...


class CaptureRepository(Protocol):
    async def add(self, capture: CapturedSource) -> CapturedSource: ...
    async def get(self, capture_id: str) -> CapturedSource | None: ...
    async def list(self, limit: int = 50) -> list[CapturedSource]: ...
    async def find_by_source_key(self, source_key: str) -> CapturedSource | None: ...
    async def update(self, capture: CapturedSource) -> CapturedSource: ...
    async def mark_downloaded(self, capture_id: str) -> CapturedSource | None: ...
    async def delete(self, capture_id: str) -> None: ...
