import json
import os
import time
from pathlib import Path

_SESSION_FILENAME_SUFFIX = '_session_cookies.txt'


def session_cookie_file(database_path: Path, platform: str) -> Path:
    """Dedicated file per platform, separate from the main SQLite DB so it
    can be excluded from backup/export tooling on its own."""
    return database_path.parent / f'{platform}{_SESSION_FILENAME_SUFFIX}'


def _parse_cookie_header(cookie_header: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for part in cookie_header.split(';'):
        part = part.strip()
        if not part or '=' not in part:
            continue
        name, _, value = part.partition('=')
        name = name.strip()
        value = value.strip()
        if name:
            pairs.append((name, value))
    return pairs


def _parse_cookie_json(raw: str) -> list[tuple[str, str]] | None:
    """Browser cookie-export extensions (Cookie-Editor, EditThisCookie,
    "Get cookies.txt LOCALLY") commonly export a JSON array of
    ``{"name": ..., "value": ..., ...}`` objects, or occasionally a plain
    ``{"name": "value", ...}`` map. Returns None (not an error) when the
    input isn't JSON at all, so the caller can fall back to the raw
    ``Cookie:`` header format.
    """
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return None

    pairs: list[tuple[str, str]] = []
    if isinstance(parsed, list):
        for entry in parsed:
            if not isinstance(entry, dict):
                continue
            name = entry.get('name')
            value = entry.get('value')
            if isinstance(name, str) and name and isinstance(value, str):
                pairs.append((name, value))
    elif isinstance(parsed, dict):
        for name, value in parsed.items():
            if isinstance(name, str) and name and isinstance(value, str):
                pairs.append((name, value))
    return pairs


def _parse_cookie_input(raw: str) -> list[tuple[str, str]]:
    json_pairs = _parse_cookie_json(raw)
    if json_pairs is not None:
        return json_pairs
    return _parse_cookie_header(raw)


def save_session_cookie(database_path: Path, platform: str, domain: str, cookie_header: str) -> int:
    """Store a user-pasted browser session as a Netscape-format cookies.txt
    file, the format gallery-dl's ``--cookies FILE`` reads. Accepts either
    the raw ``Cookie:`` header string (``name=value; name2=value2``) or a
    JSON cookie export from a browser extension (an array of
    ``{"name", "value", ...}`` objects, or a plain name->value map).

    PocketDL never asks for or stores a password -- only a session cookie the
    user exports from their own already-authenticated browser session. The
    file is never included in any API response; callers only ever expose a
    `configured: bool` derived from `has_session_cookie`. Returns the number
    of individual cookies parsed, for a confirmation message.
    """
    pairs = _parse_cookie_input(cookie_header)
    if not pairs:
        raise ValueError('No cookies found in the pasted value. Paste either a Cookie header or a JSON cookie export.')

    path = session_cookie_file(database_path, platform)
    path.parent.mkdir(parents=True, exist_ok=True)
    expires = int(time.time()) + 365 * 24 * 3600
    lines = ['# Netscape HTTP Cookie File -- generated by PocketDL. Do not share this file.']
    for name, value in pairs:
        lines.append('\t'.join([domain, 'TRUE', '/', 'TRUE', str(expires), name, value]))
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    try:
        # Best-effort on every platform; on Windows this does not enforce a
        # real ACL, but it does at least clear the world-writable bit and
        # signals intent for anyone inspecting the file's mode.
        os.chmod(path, 0o600)
    except OSError:
        pass
    return len(pairs)


def has_session_cookie(database_path: Path, platform: str) -> bool:
    return session_cookie_file(database_path, platform).exists()


def load_cookie_pairs(database_path: Path, platform: str) -> dict[str, str]:
    """Read the stored Netscape cookies.txt back into a plain name->value
    dict, for an engine that wants to inject cookies directly into its own
    HTTP session (e.g. instaloader's ``context.update_cookies``) rather
    than reading a file path (gallery-dl's ``--cookies FILE``). One storage
    format, two readers -- returns {} rather than raising when nothing is
    configured, since "no session" is an ordinary, expected state here.
    """
    path = session_cookie_file(database_path, platform)
    if not path.exists():
        return {}
    try:
        content = path.read_text(encoding='utf-8')
    except OSError:
        return {}

    pairs: dict[str, str] = {}
    for line in content.splitlines():
        if line.startswith('#') or not line.strip():
            continue
        fields = line.split('\t')
        if len(fields) >= 7:
            pairs[fields[5]] = fields[6]
    return pairs


def clear_session_cookie(database_path: Path, platform: str) -> None:
    try:
        session_cookie_file(database_path, platform).unlink()
    except FileNotFoundError:
        pass


def scrub_cookie_values(text: str, database_path: Path, platform: str) -> str:
    """Redact any pasted cookie value that leaked into subprocess output
    (e.g. verbose/debug logging from the download engine) before it is
    persisted into job.error_details or written to logs. Defense in depth --
    normal operation never passes the raw cookie value on the command line,
    only the file path, but the engine's own output is not under our
    control.
    """
    path = session_cookie_file(database_path, platform)
    if not path.exists():
        return text
    try:
        content = path.read_text(encoding='utf-8')
    except OSError:
        return text

    redacted = text
    for line in content.splitlines():
        if line.startswith('#') or not line.strip():
            continue
        fields = line.split('\t')
        if len(fields) >= 7:
            value = fields[6]
            if value and value in redacted:
                redacted = redacted.replace(value, '***REDACTED***')
    return redacted
